// from: https://xkcd.com/color/rgb.txt
pub const COLORS: &[&str] = &[
    "acid green",
    "adobe",
    "algae",
    "algae green",
    "almost black",
    "amber",
    "amethyst",
    "apple",
    "apple green",
    "apricot",
    "aqua",
    "aqua blue",
    "aqua green",
    "aqua marine",
    "aquamarine",
    "army green",
    "asparagus",
    "aubergine",
    "auburn",
    "avocado",
    "avocado green",
    "azul",
    "azure",
    "baby blue",
    "baby green",
    "baby pink",
    "baby poo",
    "baby poop",
    "baby poop green",
    "baby puke green",
    "baby purple",
    "baby shit brown",
    "baby shit green",
    "banana",
    "banana yellow",
    "barbie pink",
    "barf green",
    "barney",
    "barney purple",
    "battleship grey",
    "beige",
    "berry",
    "bile",
    "black",
    "bland",
    "blood",
    "blood orange",
    "blood red",
    "blue",
    "blueberry",
    "blue blue",
    "blue green",
    "blue/green",
    "bluegreen",
    "blue grey",
    "blue/grey",
    "bluegrey",
    "blue purple",
    "blue/purple",
    "blue violet",
    "blue with a hint of purple",
    "bluey green",
    "bluey grey",
    "bluey purple",
    "bluish",
    "bluish green",
    "bluish grey",
    "bluish purple",
    "blurple",
    "blush",
    "blush pink",
    "booger",
    "booger green",
    "bordeaux",
    "boring green",
    "bottle green",
    "brick",
    "brick orange",
    "brick red",
    "bright aqua",
    "bright blue",
    "bright cyan",
    "bright green",
    "bright lavender",
    "bright light blue",
    "bright light green",
    "bright lilac",
    "bright lime",
    "bright lime green",
    "bright magenta",
    "bright olive",
    "bright orange",
    "bright pink",
    "bright purple",
    "bright red",
    "bright sea green",
    "bright sky blue",
    "bright teal",
    "bright turquoise",
    "bright violet",
    "bright yellow",
    "bright yellow green",
    "british racing green",
    "bronze",
    "brown",
    "brown green",
    "brown grey",
    "brownish",
    "brownish green",
    "brownish grey",
    "brownish orange",
    "brownish pink",
    "brownish purple",
    "brownish red",
    "brownish yellow",
    "brown orange",
    "brown red",
    "brown yellow",
    "browny green",
    "browny orange",
    "bruise",
    "bubblegum",
    "bubble gum pink",
    "bubblegum pink",
    "buff",
    "burgundy",
    "burnt orange",
    "burnt red",
    "burnt siena",
    "burnt sienna",
    "burnt umber",
    "burnt yellow",
    "burple",
    "butter",
    "butterscotch",
    "butter yellow",
    "cadet blue",
    "camel",
    "camo",
    "camo green",
    "camouflage green",
    "canary",
    "canary yellow",
    "candy pink",
    "caramel",
    "carmine",
    "carnation",
    "carnation pink",
    "carolina blue",
    "celadon",
    "celery",
    "cement",
    "cerise",
    "cerulean",
    "cerulean blue",
    "charcoal",
    "charcoal grey",
    "chartreuse",
    "cherry",
    "cherry red",
    "chestnut",
    "chocolate",
    "chocolate brown",
    "cinnamon",
    "claret",
    "clay",
    "clay brown",
    "clear blue",
    "cloudy blue",
    "cobalt",
    "cobalt blue",
    "cocoa",
    "coffee",
    "cool blue",
    "cool green",
    "cool grey",
    "copper",
    "coral",
    "coral pink",
    "cornflower",
    "cornflower blue",
    "cranberry",
    "cream",
    "creme",
    "crimson",
    "custard",
    "cyan",
    "dandelion",
    "dark",
    "dark aqua",
    "dark aquamarine",
    "dark beige",
    "dark blue",
    "darkblue",
    "dark blue green",
    "dark blue grey",
    "dark brown",
    "dark coral",
    "dark cream",
    "dark cyan",
    "dark forest green",
    "dark fuchsia",
    "dark gold",
    "dark grass green",
    "dark green",
    "darkgreen",
    "dark green blue",
    "dark grey",
    "dark grey blue",
    "dark hot pink",
    "dark indigo",
    "darkish blue",
    "darkish green",
    "darkish pink",
    "darkish purple",
    "darkish red",
    "dark khaki",
    "dark lavender",
    "dark lilac",
    "dark lime",
    "dark lime green",
    "dark magenta",
    "dark maroon",
    "dark mauve",
    "dark mint",
    "dark mint green",
    "dark mustard",
    "dark navy",
    "dark navy blue",
    "dark olive",
    "dark olive green",
    "dark orange",
    "dark pastel green",
    "dark peach",
    "dark periwinkle",
    "dark pink",
    "dark plum",
    "dark purple",
    "dark red",
    "dark rose",
    "dark royal blue",
    "dark sage",
    "dark salmon",
    "dark sand",
    "dark seafoam",
    "dark seafoam green",
    "dark sea green",
    "dark sky blue",
    "dark slate blue",
    "dark tan",
    "dark taupe",
    "dark teal",
    "dark turquoise",
    "dark violet",
    "dark yellow",
    "dark yellow green",
    "deep aqua",
    "deep blue",
    "deep brown",
    "deep green",
    "deep lavender",
    "deep lilac",
    "deep magenta",
    "deep orange",
    "deep pink",
    "deep purple",
    "deep red",
    "deep rose",
    "deep sea blue",
    "deep sky blue",
    "deep teal",
    "deep turquoise",
    "deep violet",
    "denim",
    "denim blue",
    "desert",
    "diarrhea",
    "dirt",
    "dirt brown",
    "dirty blue",
    "dirty green",
    "dirty orange",
    "dirty pink",
    "dirty purple",
    "dirty yellow",
    "dodger blue",
    "drab",
    "drab green",
    "dried blood",
    "duck egg blue",
    "dull blue",
    "dull brown",
    "dull green",
    "dull orange",
    "dull pink",
    "dull purple",
    "dull red",
    "dull teal",
    "dull yellow",
    "dusk",
    "dusk blue",
    "dusky blue",
    "dusky pink",
    "dusky purple",
    "dusky rose",
    "dust",
    "dusty blue",
    "dusty green",
    "dusty lavender",
    "dusty orange",
    "dusty pink",
    "dusty purple",
    "dusty red",
    "dusty rose",
    "dusty teal",
    "earth",
    "easter green",
    "easter purple",
    "ecru",
    "eggplant",
    "eggplant purple",
    "egg shell",
    "eggshell",
    "eggshell blue",
    "electric blue",
    "electric green",
    "electric lime",
    "electric pink",
    "electric purple",
    "emerald",
    "emerald green",
    "evergreen",
    "faded blue",
    "faded green",
    "faded orange",
    "faded pink",
    "faded purple",
    "faded red",
    "faded yellow",
    "fawn",
    "fern",
    "fern green",
    "fire engine red",
    "flat blue",
    "flat green",
    "fluorescent green",
    "fluro green",
    "foam green",
    "forest",
    "forest green",
    "forrest green",
    "french blue",
    "fresh green",
    "frog green",
    "fuchsia",
    "gold",
    "golden",
    "golden brown",
    "golden rod",
    "goldenrod",
    "golden yellow",
    "grape",
    "grapefruit",
    "grape purple",
    "grass",
    "grass green",
    "grassy green",
    "green",
    "green apple",
    "green blue",
    "green/blue",
    "greenblue",
    "green brown",
    "green grey",
    "greenish",
    "greenish beige",
    "greenish blue",
    "greenish brown",
    "greenish cyan",
    "greenish grey",
    "greenish tan",
    "greenish teal",
    "greenish turquoise",
    "greenish yellow",
    "green teal",
    "greeny blue",
    "greeny brown",
    "green yellow",
    "green/yellow",
    "greeny grey",
    "greeny yellow",
    "grey",
    "grey blue",
    "grey/blue",
    "greyblue",
    "grey brown",
    "grey green",
    "grey/green",
    "greyish",
    "greyish blue",
    "greyish brown",
    "greyish green",
    "greyish pink",
    "greyish purple",
    "greyish teal",
    "grey pink",
    "grey purple",
    "grey teal",
    "gross green",
    "gunmetal",
    "hazel",
    "heather",
    "heliotrope",
    "highlighter green",
    "hospital green",
    "hot green",
    "hot magenta",
    "hot pink",
    "hot purple",
    "hunter green",
    "ice",
    "ice blue",
    "icky green",
    "indian red",
    "indigo",
    "indigo blue",
    "iris",
    "irish green",
    "ivory",
    "jade",
    "jade green",
    "jungle green",
    "kelley green",
    "kelly green",
    "kermit green",
    "key lime",
    "khaki",
    "khaki green",
    "kiwi",
    "kiwi green",
    "lavender",
    "lavender blue",
    "lavender pink",
    "lawn green",
    "leaf",
    "leaf green",
    "leafy green",
    "leather",
    "lemon",
    "lemon green",
    "lemon lime",
    "lemon yellow",
    "lichen",
    "light aqua",
    "light aquamarine",
    "light beige",
    "light blue",
    "lightblue",
    "light blue green",
    "light blue grey",
    "light bluish green",
    "light bright green",
    "light brown",
    "light burgundy",
    "light cyan",
    "light eggplant",
    "lighter green",
    "lighter purple",
    "light forest green",
    "light gold",
    "light grass green",
    "light green",
    "lightgreen",
    "light green blue",
    "light greenish blue",
    "light grey",
    "light grey blue",
    "light grey green",
    "light indigo",
    "lightish blue",
    "lightish green",
    "lightish purple",
    "lightish red",
    "light khaki",
    "light lavendar",
    "light lavender",
    "light light blue",
    "light light green",
    "light lilac",
    "light lime",
    "light lime green",
    "light magenta",
    "light maroon",
    "light mauve",
    "light mint",
    "light mint green",
    "light moss green",
    "light mustard",
    "light navy",
    "light navy blue",
    "light neon green",
    "light olive",
    "light olive green",
    "light orange",
    "light pastel green",
    "light peach",
    "light pea green",
    "light periwinkle",
    "light pink",
    "light plum",
    "light purple",
    "light red",
    "light rose",
    "light royal blue",
    "light sage",
    "light salmon",
    "light seafoam",
    "light seafoam green",
    "light sea green",
    "light sky blue",
    "light tan",
    "light teal",
    "light turquoise",
    "light urple",
    "light violet",
    "light yellow",
    "light yellow green",
    "light yellowish green",
    "lilac",
    "liliac",
    "lime",
    "lime green",
    "lime yellow",
    "lipstick",
    "lipstick red",
    "macaroni and cheese",
    "magenta",
    "mahogany",
    "maize",
    "mango",
    "manilla",
    "marigold",
    "marine",
    "marine blue",
    "maroon",
    "mauve",
    "medium blue",
    "medium brown",
    "medium green",
    "medium grey",
    "medium pink",
    "medium purple",
    "melon",
    "merlot",
    "metallic blue",
    "mid blue",
    "mid green",
    "midnight",
    "midnight blue",
    "midnight purple",
    "military green",
    "milk chocolate",
    "mint",
    "mint green",
    "minty green",
    "mocha",
    "moss",
    "moss green",
    "mossy green",
    "mud",
    "mud brown",
    "muddy brown",
    "muddy green",
    "muddy yellow",
    "mud green",
    "mulberry",
    "murky green",
    "mushroom",
    "mustard",
    "mustard brown",
    "mustard green",
    "mustard yellow",
    "muted blue",
    "muted green",
    "muted pink",
    "muted purple",
    "nasty green",
    "navy",
    "navy blue",
    "navy green",
    "neon blue",
    "neon green",
    "neon pink",
    "neon purple",
    "neon red",
    "neon yellow",
    "nice blue",
    "night blue",
    "ocean",
    "ocean blue",
    "ocean green",
    "ocher",
    "ochre",
    "ocre",
    "off blue",
    "off green",
    "off white",
    "off yellow",
    "old pink",
    "old rose",
    "olive",
    "olive brown",
    "olive drab",
    "olive green",
    "olive yellow",
    "orange",
    "orange brown",
    "orangeish",
    "orange pink",
    "orange red",
    "orangered",
    "orangey brown",
    "orange yellow",
    "orangey red",
    "orangey yellow",
    "orangish",
    "orangish brown",
    "orangish red",
    "orchid",
    "pale",
    "pale aqua",
    "pale blue",
    "pale brown",
    "pale cyan",
    "pale gold",
    "pale green",
    "pale grey",
    "pale lavender",
    "pale light green",
    "pale lilac",
    "pale lime",
    "pale lime green",
    "pale magenta",
    "pale mauve",
    "pale olive",
    "pale olive green",
    "pale orange",
    "pale peach",
    "pale pink",
    "pale purple",
    "pale red",
    "pale rose",
    "pale salmon",
    "pale sky blue",
    "pale teal",
    "pale turquoise",
    "pale violet",
    "pale yellow",
    "parchment",
    "pastel blue",
    "pastel green",
    "pastel orange",
    "pastel pink",
    "pastel purple",
    "pastel red",
    "pastel yellow",
    "pea",
    "peach",
    "peachy pink",
    "peacock blue",
    "pea green",
    "pear",
    "pea soup",
    "pea soup green",
    "periwinkle",
    "periwinkle blue",
    "perrywinkle",
    "petrol",
    "pig pink",
    "pine",
    "pine green",
    "pink",
    "pinkish",
    "pinkish brown",
    "pinkish grey",
    "pinkish orange",
    "pinkish purple",
    "pinkish red",
    "pinkish tan",
    "pink purple",
    "pink/purple",
    "pink red",
    "pinky",
    "pinky purple",
    "pinky red",
    "piss yellow",
    "pistachio",
    "plum",
    "plum purple",
    "poison green",
    "poo",
    "poo brown",
    "poop",
    "poop brown",
    "poop green",
    "powder blue",
    "powder pink",
    "primary blue",
    "prussian blue",
    "puce",
    "puke",
    "puke brown",
    "puke green",
    "puke yellow",
    "pumpkin",
    "pumpkin orange",
    "pure blue",
    "purple",
    "purple blue",
    "purple/blue",
    "purple brown",
    "purple grey",
    "purpleish",
    "purpleish blue",
    "purpleish pink",
    "purple pink",
    "purple/pink",
    "purple red",
    "purpley",
    "purpley blue",
    "purpley grey",
    "purpley pink",
    "purplish",
    "purplish blue",
    "purplish brown",
    "purplish grey",
    "purplish pink",
    "purplish red",
    "purply",
    "purply blue",
    "purply pink",
    "putty",
    "racing green",
    "radioactive green",
    "raspberry",
    "raw sienna",
    "raw umber",
    "really light blue",
    "red",
    "red brown",
    "reddish",
    "reddish brown",
    "reddish grey",
    "reddish orange",
    "reddish pink",
    "reddish purple",
    "reddy brown",
    "red orange",
    "red pink",
    "red purple",
    "red violet",
    "red wine",
    "rich blue",
    "rich purple",
    "robin egg blue",
    "robin's egg",
    "robin's egg blue",
    "rosa",
    "rose",
    "rose pink",
    "rose red",
    "rosy pink",
    "rouge",
    "royal",
    "royal blue",
    "royal purple",
    "ruby",
    "russet",
    "rust",
    "rust brown",
    "rust orange",
    "rust red",
    "rusty orange",
    "rusty red",
    "saffron",
    "sage",
    "sage green",
    "salmon",
    "salmon pink",
    "sand",
    "sand brown",
    "sandstone",
    "sandy",
    "sandy brown",
    "sand yellow",
    "sandy yellow",
    "sap green",
    "sapphire",
    "scarlet",
    "sea",
    "sea blue",
    "seafoam",
    "seafoam blue",
    "seafoam green",
    "sea green",
    "seaweed",
    "seaweed green",
    "sepia",
    "shamrock",
    "shamrock green",
    "shit",
    "shit brown",
    "shit green",
    "shocking pink",
    "sick green",
    "sickly green",
    "sickly yellow",
    "sienna",
    "silver",
    "sky",
    "sky blue",
    "slate",
    "slate blue",
    "slate green",
    "slate grey",
    "slime green",
    "snot",
    "snot green",
    "soft blue",
    "soft green",
    "soft pink",
    "soft purple",
    "spearmint",
    "spring green",
    "spruce",
    "squash",
    "steel",
    "steel blue",
    "steel grey",
    "stone",
    "stormy blue",
    "straw",
    "strawberry",
    "strong blue",
    "strong pink",
    "sunflower",
    "sunflower yellow",
    "sunny yellow",
    "sunshine yellow",
    "sun yellow",
    "swamp",
    "swamp green",
    "tan",
    "tan brown",
    "tangerine",
    "tan green",
    "taupe",
    "tea",
    "tea green",
    "teal",
    "teal blue",
    "teal green",
    "tealish",
    "tealish green",
    "terracota",
    "terra cotta",
    "terracotta",
    "tiffany blue",
    "tomato",
    "tomato red",
    "topaz",
    "toupe",
    "toxic green",
    "tree green",
    "true blue",
    "true green",
    "turquoise",
    "turquoise blue",
    "turquoise green",
    "turtle green",
    "twilight",
    "twilight blue",
    "ugly blue",
    "ugly brown",
    "ugly green",
    "ugly pink",
    "ugly purple",
    "ugly yellow",
    "ultramarine",
    "ultramarine blue",
    "umber",
    "velvet",
    "vermillion",
    "very dark blue",
    "very dark brown",
    "very dark green",
    "very dark purple",
    "very light blue",
    "very light brown",
    "very light green",
    "very light pink",
    "very light purple",
    "very pale blue",
    "very pale green",
    "vibrant blue",
    "vibrant green",
    "vibrant purple",
    "violet",
    "violet blue",
    "violet pink",
    "violet red",
    "viridian",
    "vivid blue",
    "vivid green",
    "vivid purple",
    "vomit",
    "vomit green",
    "vomit yellow",
    "warm blue",
    "warm brown",
    "warm grey",
    "warm pink",
    "warm purple",
    "washed out green",
    "water blue",
    "watermelon",
    "weird green",
    "wheat",
    "white",
    "windows blue",
    "wine",
    "wine red",
    "wintergreen",
    "wisteria",
    "yellow",
    "yellow brown",
    "yellow green",
    "yellow/green",
    "yellowgreen",
    "yellowish",
    "yellowish brown",
    "yellowish green",
    "yellowish orange",
    "yellowish tan",
    "yellow ochre",
    "yellow orange",
    "yellow tan",
    "yellowy brown",
    "yellowy green",
];
